gpt_researcher::master::prompts
dict gpt_researcher::master::prompts.report_type_mapping
gpt_researcher.master.prompts.generate_search_queries_prompt(str question, str parent_query, str report_type, int max_iterations=3)
Generates the search queries prompt for the given question. Args: question (str): The question to generate the search queries prompt for parent_query (str): The main question (only relevant for detailed reports) report_type (str): The report type max_iterations (int): The maximum number of search queries to generate Returns: str: The search queries prompt for the given question
Referenced by gpt_researcher.master.actions.get_sub_queries.
gpt_researcher.master.prompts.generate_report_prompt(str question, context, str report_source, report_format="apa", total_words=1000)
Generates the report prompt for the given question and research summary. Args: question (str): The question to generate the report prompt for research_summary (str): The research summary to generate the report prompt for Returns: str: The report prompt for the given question and research summary
gpt_researcher.master.prompts.generate_resource_report_prompt(question, context, str report_source, report_format="apa", total_words=1000)
Generates the resource report prompt for the given question and research summary. Args: question (str): The question to generate the resource report prompt for. context (str): The research summary to generate the resource report prompt for. Returns: str: The resource report prompt for the given question and research summary.
gpt_researcher.master.prompts.generate_custom_report_prompt(query_prompt, context, str report_source, report_format="apa", total_words=1000)
gpt_researcher.master.prompts.generate_outline_report_prompt(question, context, str report_source, report_format="apa", total_words=1000)
Generates the outline report prompt for the given question and research summary. Args: question (str): The question to generate the outline report prompt for research_summary (str): The research summary to generate the outline report prompt for Returns: str: The outline report prompt for the given question and research summary
gpt_researcher.master.prompts.get_report_by_type(str report_type)
gpt_researcher.master.prompts.auto_agent_instructions()
gpt_researcher.master.prompts.generate_summary_prompt(query, data)
Generates the summary prompt for the given question and text. Args: question (str): The question to generate the summary prompt for text (str): The text to generate the summary prompt for Returns: str: The summary prompt for the given question and text
str gpt_researcher.master.prompts.generate_subtopics_prompt()
str gpt_researcher.master.prompts.generate_subtopic_report_prompt(current_subtopic, list existing_headers, str main_topic, context, str report_format="apa", max_subsections=5, total_words=800)
str gpt_researcher.master.prompts.generate_report_introduction(str question, str research_summary="")
Referenced by gpt_researcher.master.actions.get_report_introduction.
gpt_researcher.master.prompts.get_prompt_by_report_type(report_type)
Referenced by gpt_researcher.master.agent.GPTResearcher.__init__, gpt_researcher.master.actions.generate_report.