users
users.HOST
users.APP_PORT
str users.API_URL
users.key
users.type
users.on_click
users.new_username
users.new_email
users.new_password
users.new_is_admin
users.submit_button
users.delete_user_id
users.login(username, password)
Авторизация пользователя и получение токена
Referenced by on_login_clicked.
users.refresh_access_token(refresh_token)
Обновление токена доступа
Referenced by get_valid_access_token.
users.fetch_users()
Получение списка пользователей
References get_valid_access_token.
Referenced by display_users.
users.display_users()
References delete_user, fetch_users, modify_user.
users.modify_user(token, user_data)
Referenced by display_users.
users.create_user(token, username, email, password, is_admin)
Создание нового пользователя
users.delete_user(token, user_id)
Удаление пользователя
Referenced by display_users.
users.get_valid_access_token()
References refresh_access_token.
Referenced by fetch_users.
users.main()
users.on_login_clicked()
References login.