gpt_researcher::master::actions
gpt_researcher.master.actions.get_retriever(retriever)
Gets the retriever Args: retriever: retriever name Returns: retriever: Retriever class
gpt_researcher.master.actions.choose_agent(query, cfg, parent_query=None, callable cost_callback=None)
Chooses the agent automatically Args: parent_query: In some cases the research is conducted on a subtopic from the main query. The parent query allows the agent to know the main context for better reasoning. query: original query cfg: Config cost_callback: callback for calculating llm costs Returns: agent: Agent name agent_role_prompt: Agent role prompt
gpt_researcher.master.actions.get_sub_queries(str query, str agent_role_prompt, cfg, str parent_query, str report_type, callable cost_callback=None)
Gets the sub queries Args: query: original query agent_role_prompt: agent role prompt cfg: Config parent_query: report_type: cost_callback: Returns: sub_queries: List of sub queries
References gpt_researcher.master.prompts.generate_search_queries_prompt.
Referenced by gpt_researcher.master.agent.GPTResearcher.__get_context_by_search.
gpt_researcher.master.actions.scrape_urls(urls, cfg=None)
Scrapes the urls Args: urls: List of urls cfg: Config (optional) Returns: text: str
Referenced by gpt_researcher.master.agent.GPTResearcher.__get_context_by_urls, gpt_researcher.master.agent.GPTResearcher.__scrape_data_by_query.
gpt_researcher.master.actions.summarize(query, content, agent_role_prompt, cfg, websocket=None, callable cost_callback=None)
Asynchronously summarizes a list of URLs. Args: query (str): The search query. content (list): List of dictionaries with 'url' and 'raw_content'. agent_role_prompt (str): The role prompt for the agent. cfg (object): Configuration object. Returns: list: A list of dictionaries with 'url' and 'summary'.
References gpt_researcher.master.actions.stream_output, gpt_researcher.master.actions.summarize_url.
gpt_researcher.master.actions.summarize_url(query, raw_data, agent_role_prompt, cfg, callable cost_callback=None)
Summarizes the text Args: query: raw_data: agent_role_prompt: cfg: cost_callback Returns: summary: str
Referenced by gpt_researcher.master.actions.summarize.
gpt_researcher.master.actions.generate_report(str query, context, str agent_role_prompt, str report_type, str report_source, websocket, cfg, str main_topic="", list existing_headers=[], callable cost_callback=None)
generates the final report Args: query: context: agent_role_prompt: report_type: websocket: cfg: main_topic: existing_headers: cost_callback: Returns: report:
References gpt_researcher.master.prompts.get_prompt_by_report_type.
gpt_researcher.master.actions.stream_output(type, output, websocket=None, logging=True)
Streams output to the websocket Args: type: output: Returns: None
Referenced by gpt_researcher.master.agent.GPTResearcher.__get_context_by_search, gpt_researcher.master.agent.GPTResearcher.__get_context_by_urls, gpt_researcher.master.agent.GPTResearcher.__get_new_urls, gpt_researcher.master.agent.GPTResearcher.__get_similar_content_by_query, gpt_researcher.master.agent.GPTResearcher.__process_sub_query, gpt_researcher.master.agent.GPTResearcher.__scrape_data_by_query, gpt_researcher.master.agent.GPTResearcher.conduct_research, gpt_researcher.master.agent.GPTResearcher.get_subtopics, gpt_researcher.master.actions.summarize, gpt_researcher.master.agent.GPTResearcher.write_report.
gpt_researcher.master.actions.get_report_introduction(query, context, role, config, websocket=None, callable cost_callback=None)
References gpt_researcher.master.prompts.generate_report_introduction.
Referenced by gpt_researcher.master.agent.GPTResearcher.write_introduction.
gpt_researcher.master.actions.extract_headers(str markdown_text)
gpt_researcher.master.actions.table_of_contents(str markdown_text)
gpt_researcher.master.actions.add_source_urls(str report_markdown, set visited_urls)
This function takes a Markdown report and a set of visited URLs as input parameters. Args: report_markdown (str): The `add_source_urls` function takes in two parameters: visited_urls (set): Visited_urls is a set that contains URLs that have already been visited. This parameter is used to keep track of which URLs have already been included in the report_markdown to avoid duplication.