processing::text
Generator[str, None, None] processing.text.split_text(str text, int max_length=8192)
Split text into chunks of a maximum length Args: text (str): The text to split max_length (int, optional): The maximum length of each chunk. Defaults to 8192. Yields: str: The next chunk of text Raises: ValueError: If the text is longer than the maximum length
Referenced by processing.text.summarize_text.
str processing.text.summarize_text(str fast_llm_model, int summary_token_limit, str llm_provider, str url, str text, str question, Optional[WebDriver] driver=None)
Summarize text using the OpenAI API Args: fast_llm_model (str): The fast LLM model e.g gpt3.5-turbo-16k summary_token_limit (int): The summary token limit llm_provider (str): The llm provider url (str): The url of the text text (str): The text to summarize question (str): The question to ask the model driver (WebDriver): The webdriver to use to scroll the page Returns: str: The summary of the text
References processing.text.create_message, processing.text.scroll_to_percentage, processing.text.split_text.
None processing.text.scroll_to_percentage(WebDriver driver, float ratio)
Scroll to a percentage of the page Args: driver (WebDriver): The webdriver to use ratio (float): The percentage to scroll to Raises: ValueError: If the ratio is not between 0 and 1
Referenced by processing.text.summarize_text.
Dict[str, str] processing.text.create_message(str chunk, str question)
Create a message for the chat completion Args: chunk (str): The chunk of text to summarize question (str): The question to answer Returns: Dict[str, str]: The message to send to the chat completion
Referenced by processing.text.summarize_text.
None processing.text.write_to_file(str filename, str text)
Write text to a file Args: text (str): The text to write filename (str): The filename to write to
Referenced by processing.text.write_md_to_pdf.
None processing.text.write_md_to_pdf(str task, str path, str text)
References processing.text.md_to_pdf, processing.text.write_to_file.
processing.text.read_txt_files(directory)
processing.text.md_to_pdf(input_file, output_file)
Referenced by processing.text.write_md_to_pdf.