web_scrape
web_scrape.executor
web_scrape.FILE_DIR
str web_scrape.async_browse(str selenium_web_browser, str user_agent, str fast_llm_model, str summary_token_limit, str llm_provider, str url, str question, WebSocket websocket)
Browse a website and return the answer and links to the user Args: selenium_web_browser (str): The web browser used for scraping user_agent (str): The user agent used when scraping url (str): The url of the website to browse question (str): The question asked by the user websocket (WebSocketManager): The websocket manager Returns: str: The answer and links to the user
tuple[str, WebDriver] web_scrape.browse_website(str url, str question)
Browse a website and return the answer and links to the user Args: url (str): The url of the website to browse question (str): The question asked by the user Returns: Tuple[str, WebDriver]: The answer and links to the user and the webdriver
References add_header, close_browser, scrape_links_with_selenium, scrape_text_with_selenium.
tuple[WebDriver, str] web_scrape.scrape_text_with_selenium(str selenium_web_browser, str user_agent, str url)
Scrape text from a website using selenium Args: url (str): The url of the website to scrape selenium_web_browser (str): The web browser used to scrape user_agent (str): The user agent used when scraping Returns: Tuple[WebDriver, str]: The webdriver and the text scraped from the website
References get_text, scrape_skills.scrape_pdf_with_arxiv, scrape_skills.scrape_pdf_with_pymupdf.
Referenced by browse_website.
web_scrape.get_text(soup)
Get the text from the soup Args: soup (BeautifulSoup): The soup to get the text from Returns: str: The text from the soup
Referenced by scrape_text_with_selenium.
list[str] web_scrape.scrape_links_with_selenium(WebDriver driver, str url)
Scrape links from a website using selenium Args: driver (WebDriver): The webdriver to use to scrape the links Returns: List[str]: The links scraped from the website
Referenced by browse_website.
None web_scrape.close_browser(WebDriver driver)
Close the browser Args: driver (WebDriver): The webdriver to close Returns: None
Referenced by browse_website.
None web_scrape.add_header(WebDriver driver)
Add a header to the website Args: driver (WebDriver): The webdriver to use to add the header Returns: None
Referenced by browse_website.