gpt_researcher::utils::llm
gpt_researcher.utils.llm.get_llm(llm_provider, **kwargs)
Referenced by gpt_researcher.utils.llm.construct_subtopics, gpt_researcher.utils.llm.create_chat_completion.
str gpt_researcher.utils.llm.create_chat_completion(list messages, Optional[str] model=None, float temperature=1.0, Optional[int] max_tokens=None, Optional[str] llm_provider=None, Optional[bool] stream=False, WebSocket|None websocket=None, Dict[str, Any]|None llm_kwargs=None, callable cost_callback=None)
Create a chat completion using the OpenAI API Args: messages (list[dict[str, str]]): The messages to send to the chat completion model (str, optional): The model to use. Defaults to None. temperature (float, optional): The temperature to use. Defaults to 0.9. max_tokens (int, optional): The max tokens to use. Defaults to None. stream (bool, optional): Whether to stream the response. Defaults to False. llm_provider (str, optional): The LLM Provider to use. webocket (WebSocket): The websocket used in the currect request, cost_callback: Callback function for updating cost Returns: str: The response from the chat completion
References gpt_researcher.utils.llm.get_llm.
list gpt_researcher.utils.llm.construct_subtopics(str task, str data, config, list subtopics=[])
References gpt_researcher.utils.llm.get_llm.
Referenced by gpt_researcher.master.agent.GPTResearcher.get_subtopics.